### PR TITLE
Add the Code of Conduct page

### LINKED ISSUE #9: Let's add a Code of Conduct
We can just steal the one from [Dallas Nodeschool](http://nodeschool.io/dallas/code-of-conduct/), but it should be personalized to reflect Denton.

### PR DESCRIPTION
**Pull request by nikhilgupta23**
The content of the page has been copied from [Dallas Code of Conduct](https://nodeschool.io/dallas/code-of-conduct/). Please specify if any changes are required.
(This PR fixes #9)

### CODE REVIEW

**Comment by newswim** [comment]
This is great, thank you!

Some of the wording needs a little tweaking, for instance the references to 'Conference' - it's probably more appropriate to say 'workshop', or omit the word altogether.

Also I wasn't able to open the link, [http://2012.jsconf.us/#/about &amp; The Ada Initiative](http://2012.jsconf.us/#/about &amp; The Ada Initiative). I'm happy to merge this now and make the changes, or if you'd like an additional commit record, go for it.

I've found the original link. [JSConf Code of Conduct](http://jsconf.com/codeofconduct.html)

**Comment by newswim** [comment]
I noticed that the links are also broken on Nodeschool Dallas' website ([repo](https://github.com/nodeschool/dallas)), they may appreciate the fixed code as well.

**Comment by nikhilgupta23** [comment]
Thanks for the feedback!
I've updated the Code of Conduct and fixed the hyperlinks.

**Review by newswim — APPROVED** [review]
This looks great!

**Pull request merged**
